Make instrumented tests run for 3 times for flakiness

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -34,32 +34,27 @@ jobs:
           cache: npm
       - run: npm ci
       - run: npm test
+  instrumented-tests-1:
+    uses: ./.github/workflows/instrumented-tests-run.yml
+  instrumented-tests-2:
+    needs: instrumented-tests-1
+    if: always() && needs.instrumented-tests-1.outputs.test-outcome == 'failure'
+    uses: ./.github/workflows/instrumented-tests-run.yml
+  instrumented-tests-3:
+    needs: instrumented-tests-2
+    if: always() && needs.instrumented-tests-2.outputs.test-outcome == 'failure'
+    uses: ./.github/workflows/instrumented-tests-run.yml
   instrumented-tests:
+    if: always()
+    needs: [instrumented-tests-1, instrumented-tests-2, instrumented-tests-3]
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
-        with:
-          persist-credentials: false
-      - name: Enable KVM
-        run: |
-          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
-          sudo udevadm control --reload-rules
-          sudo udevadm trigger --name-match=kvm
-      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
-        with:
-          cache: npm
-      - name: Set up JDK 21
-        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
-        with:
-          distribution: 'temurin'
-          java-version: 21
-          cache: gradle
-      - name: Run instrumented tests
-        uses: reactivecircus/android-emulator-runner@e89f39f1abbbd05b1113a29cf4db69e7540cae5a # v2.37.0
-        with:
-          api-level: 36
-          target: google_apis
-          arch: x86_64
-          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
-          disable-animations: true
-          script: ./gradlew connectedCheck --no-daemon
+      - run: |
+          if [[ "${{ needs.instrumented-tests-1.outputs.test-outcome }}" == "success" || \
+                "${{ needs.instrumented-tests-2.outputs.test-outcome }}" == "success" || \
+                "${{ needs.instrumented-tests-3.outputs.test-outcome }}" == "success" ]]; then
+            echo "Instrumented tests passed"
+            exit 0
+          fi
+          echo "All 3 attempts failed"
+          exit 1
